apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: carts-db
  name: carts-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: carts-db
    spec:
      schedulerName: scheduler
      containers:
      - image: mongo:3.4
        name: carts-db
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - all
        volumeMounts:
        - mountPath: /tmp
          name: carts-db-tmpfs0
      hostname: carts-db
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: carts-db-tmpfs0
status: {}
