apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: catalogue
    spec:
      schedulerName: scheduler
      containers:
      - image: weaveworksdemos/catalogue:0.3.5
        name: catalogue
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
      hostname: catalogue
      restartPolicy: Always
status: {}
