apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: queue-master
  name: queue-master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: queue-master
    spec:
      schedulerName: scheduler
      containers:
      - image: weaveworksdemos/queue-master:0.3.1
        name: queue-master
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: queue-master-claim0
        - mountPath: /tmp
          name: queue-master-tmpfs0
      hostname: queue-master
      restartPolicy: Always
      volumes:
      - name: queue-master-claim0
        persistentVolumeClaim:
          claimName: queue-master-claim0
      - emptyDir:
          medium: Memory
        name: queue-master-tmpfs0
status: {}
