apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user
    spec:
      schedulerName: scheduler
      containers:
      - env:
        - name: MONGO_HOST
          value: user-db:27017
        image: weaveworksdemos/user:0.4.4
        name: user
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
      hostname: user
      restartPolicy: Always
status: {}
